// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies4Joel.Models;

namespace Movies4Joel.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220126211238_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Movies4Joel.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Batman's a cool guy",
                            Rating = "PG-13",
                            Title = "Dark Knight Rises",
                            Year = (ushort)2008
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action/Advneture",
                            Director = "Jon Watts",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Spider-Man: No Way Home",
                            Year = (ushort)2021
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action/Sci-fi",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Another Nolan banger",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = (ushort)2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
